#pragma once

#define CANTASTIC_VERSION_MAJOR 2
#define CANTASTIC_VERSION_MINOR 0

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define CANTASTIC_VERSION STR(CANTASTIC_VERSION_MAJOR) "." STR(CANTASTIC_VERSION_MINOR)