/* This file is generated automatically. DO NOT EDIT. */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    NONE = 0x0,
    FRONT_BRAKE = 0x1,
    REAR_BRAKE = 0x2,
    CLUTCH = 0x3,
    SIGNAL_L = 0x4,
    SIGNAL_R = 0x5,
    SIGNAL_C = 0x6,
    SIGNAL_HAZARD = 0x7,
    FLASH = 0x8,
    FOG = 0x9,
    JOY_SEL = 0xA,
    JOY_U = 0xB,
    JOY_D = 0xC,
    JOY_L = 0xD,
    JOY_R = 0xE,
    HOME = 0xF,
    MODE = 0x10,
    SIDESTAND = 0x11,
    RIDER_SEAT_HEAT = 0x12,
    HEADLIGHT_DRL = 0x13,
    HEADLIGHT_MAIN = 0x14,
    NEUTRAL = 0x15,
    ACC_DPAD_SEL = 0x16,
    ACC_DPAD_U = 0x17,
    ACC_DPAD_D = 0x18,
    ACC_DPAD_L = 0x19,
    ACC_DPAD_R = 0x1A,
    ACC_RED = 0x1B,
    ACC_GREEN = 0x1C,
    ACC_BLUE = 0x1D,
    ACC_YELLOW = 0x1E,
    ACC_WHITE = 0x1F,
    ACC_BLACK = 0x20,
} ct_control_button_t;

static const char* ct_control_button_t_labels[33] = {
    "None", 
    "Front Brake", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    "", 
    ""
};

typedef enum {
    ACTION_NONE = 0x0,
    ACTION_PLAY_PAUSE = 0x1,
    ACTION_SKIP_FWD = 0x2,
    ACTION_SKIP_REV = 0x3,
    ACTION_VOICE_ASSIST = 0x4,
    ACTION_VOL_UP = 0x5,
    ACTION_VOL_DOWN = 0x6,
    ACTION_ESC = 0x7,
    ACTION_ENTER = 0x8,
    ACTION_UP = 0x9,
    ACTION_DOWN = 0xA,
    ACTION_LEFT = 0xB,
    ACTION_RIGHT = 0xC,
    ACTION_F1 = 0xD,
    ACTION_F2 = 0xE,
    ACTION_F3 = 0xF,
    ACTION_F4 = 0x10,
    ACTION_F5 = 0x11,
    ACTION_F6 = 0x12,
    ACTION_F7 = 0x13,
    ACTION_F8 = 0x14,
    ACTION_F9 = 0x15,
    ACTION_F10 = 0x16,
    ACTION_F11 = 0x17,
    ACTION_F12 = 0x18,
} ct_web_config_action_type_t;

#ifdef __cplusplus
}
#endif
