#pragma once

#ifdef CONFIG_CT_VEHICLE_TIGER1200_GEN3

#define VEHICLE_READ_CANBUS_BUTTONS_0x567(MSG) {\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, JOY_SEL, 1, 4)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, SIGNAL_L, 1, 6)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, FOG, 1, 8)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, JOY_L, 2, 2)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, JOY_R, 2, 4)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, HOME, 2, 8)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, JOY_U, 3, 2)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, SIGNAL_C, 3, 4)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, FLASH, 3, 6)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, JOY_D, 3, 8)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, SIGNAL_R, 4, 2)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, RIDER_SEAT_HEAT, 4, 4)\
    CANBUS_MAP_TO_BUTTON_REGISTER(MSG, MODE, 4, 6)\
}
/*
#define VEHICLE_FILTER_CANBUS(FILTER) {\
FILTER.acceptance_code = (0x567 << 21);\
FILTER.acceptance_mask = ~(TWAI_STD_ID_MASK << 21);\
FILTER.single_filter = true;\
}*/

#define VEHICLE_FILTER_CANBUS(FILTER) {\
    canbus_generate_filter(0x500, 0x600, &FILTER);\
}

#define VEHICLE_PROCESS_CANBUS(MSG) {\
    CANBUS_PROCESS_BUTTON_PACKET(0x567, MSG)\
}
